server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
file:
  dir: C:/DEV/arrivalcharm/upload
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arrivalcharm?serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    username: hong
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1009128929071-nui9ecgtob6k0ecrcg5egratlod3ajas.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: Csxx0VBkYZW6pGv4VBq_
            client-secret: e8yVl1zjqh
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: b552018e7f4ea81483cbdf8626165d86
            client-secret: ysLROpPTiUJegCT5c4uO1KAk1EVmAyZJ
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
